<#--
 * 저널 일자(journal_day) : 태그 헤더
 -->

<#--begin::Tags-->
<div class="mb-6 ms-4">
    <div id="journal_annual_day_tag_list_div" class="d-flex align-items-center mb-4 ms-4">
        <#--handlebars template goes in here-->
    </div>
    <div id="journal_annual_diary_tag_list_div" class="d-flex align-items-center mb-4 ms-4">
        <#--handlebars template goes in here-->
    </div>
    <div id="journal_annual_dream_tag_list_div" class="d-flex align-items-center mb-4 ms-4">
        <#--handlebars template goes in here-->
    </div>
</div>
