<#--
 * 저널 일자(jrnl_day) : 메타 헤더
 -->

<#--begin::Tags-->
<div class="mb-3 ms-4">
    <div class="d-flex align-items-center mb-4 ms-4">
        <div class="col-1 d-none d-md-flex ms-4 me-6 text-center fs-6">
            <b><@spring.message 'txt.day.meta'/> : </b>
        </div>
        <div class="col" id="jrnl_day_meta_list_div">
            <#--handlebars template goes in here-->
        </div>
        <div class="col-1 d-none d-md-flex ms-4 pe-0 border-2 border-gray-300 border-end h-75 w-10px">&nbsp;</div>
        <div class="col-1 d-none d-md-flex ms-4 me-20 text-center fs-6 w-auto gap-3">
            <!-- -->
        </div>
    </div>
</div>