<#--
 * 저널 일자(jrnl_day) : 메타 헤더
 -->

<#--begin::Tags-->
<div id="jrnl_meta_header" class="mb-6 ms-4 w-100">
    <div id="jrnl_day_meta_header" class="row align-items-center mb-4 ms-4 min-h-42px">
        <div class="col-auto d-none d-md-flex text-center fs-6">
            <b><@spring.message 'txt.day.meta'/> : </b>
        </div>
        <div class="col flex-grow-1" id="jrnl_day_meta_list_div">
            <#--handlebars template goes in here-->
        </div>
        <div class="col-auto d-none d-md-flex ms-4 pe-0 border-2 border-gray-300 border-end h-75 w-10px">&nbsp;</div>
        <div class="col-auto d-none d-md-flex ms-4 me-20 text-center fs-6 gap-3">&nbsp;</div>
    </div>
</div>
